-- AlterTable
ALTER TABLE `TB_COMMENT` ADD COLUMN `type` ENUM('COMMENT', 'CODE_REVIEW', 'COMMIT_REF', 'DEPLOY_LOG') NOT NULL DEFAULT 'COMMENT';

-- AlterTable
ALTER TABLE `TB_TASK` ADD COLUMN `type` ENUM('FEATURE', 'BUG', 'TECH_DEBT', 'IMPROVEMENT', 'CHORE') NOT NULL DEFAULT 'FEATURE';

-- CreateTable
CREATE TABLE `TB_TASK_CHECKLIST` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `taskId` INTEGER NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `checked` BOOLEAN NOT NULL DEFAULT false,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `TB_TASK_CHECKLIST_taskId_idx`(`taskId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TB_TASK_CHECKLIST` ADD CONSTRAINT `TB_TASK_CHECKLIST_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `TB_TASK`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
