-- CreateTable
CREATE TABLE `TB_STUDY_PLAN` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `userId` INTEGER NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `description` TEXT NULL,
    `category` ENUM('LINGUAGEM', 'FRAMEWORK', 'CERTIFICACAO', 'CONCEITO', 'CURSO', 'LIVRO') NOT NULL,
    `status` ENUM('PLANEJADO', 'EM_ANDAMENTO', 'PAUSADO', 'CONCLUIDO', 'ABANDONADO') NOT NULL DEFAULT 'PLANEJADO',
    `startDate` DATETIME(3) NULL,
    `targetDate` DATETIME(3) NULL,
    `resources` JSON NULL,
    `projectId` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,

    INDEX `TB_STUDY_PLAN_companyId_idx`(`companyId`),
    INDEX `TB_STUDY_PLAN_userId_idx`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_STUDY_TOPIC` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `planId` INTEGER NOT NULL,
    `parentId` INTEGER NULL,
    `title` VARCHAR(200) NOT NULL,
    `description` TEXT NULL,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('PENDENTE', 'ESTUDANDO', 'REVISAO', 'CONCLUIDO', 'PULADO') NOT NULL DEFAULT 'PENDENTE',
    `weight` DOUBLE NOT NULL DEFAULT 1,
    `estimateHours` DOUBLE NULL,
    `loggedHours` DOUBLE NOT NULL DEFAULT 0,
    `notes` TEXT NULL,
    `resources` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,

    INDEX `TB_STUDY_TOPIC_planId_idx`(`planId`),
    INDEX `TB_STUDY_TOPIC_parentId_idx`(`parentId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_STUDY_SESSION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `planId` INTEGER NOT NULL,
    `topicId` INTEGER NOT NULL,
    `startedAt` DATETIME(3) NOT NULL,
    `endedAt` DATETIME(3) NULL,
    `durationMin` INTEGER NULL,
    `notes` TEXT NULL,
    `confidence` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TB_STUDY_SESSION_planId_idx`(`planId`),
    INDEX `TB_STUDY_SESSION_topicId_idx`(`topicId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TB_STUDY_PLAN` ADD CONSTRAINT `TB_STUDY_PLAN_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_STUDY_PLAN` ADD CONSTRAINT `TB_STUDY_PLAN_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `USERS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_STUDY_TOPIC` ADD CONSTRAINT `TB_STUDY_TOPIC_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `TB_STUDY_PLAN`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_STUDY_TOPIC` ADD CONSTRAINT `TB_STUDY_TOPIC_parentId_fkey` FOREIGN KEY (`parentId`) REFERENCES `TB_STUDY_TOPIC`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_STUDY_SESSION` ADD CONSTRAINT `TB_STUDY_SESSION_planId_fkey` FOREIGN KEY (`planId`) REFERENCES `TB_STUDY_PLAN`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_STUDY_SESSION` ADD CONSTRAINT `TB_STUDY_SESSION_topicId_fkey` FOREIGN KEY (`topicId`) REFERENCES `TB_STUDY_TOPIC`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
