export enum RoutesEnum {
  HOME = '',
  HOME_DEFAULT = 'home',
  USER = 'user',
  USER_CREATE = 'user/create',
  USER_UPDATE = 'user/update',
  USER_PROFILE = 'user/profile',
  SETTINGS = 'settings',
  LOGIN = 'auth/login',
  GOOGLE_CALLBACK = 'auth/google/callback',
  NOT_FOUND = '404',
  // Agentic Dev Maestro
  DASHBOARD = 'dashboard',
  COMPANIES = 'companies',
  PROJECTS = 'projects',
  BOARD = 'projects/:id/board',
  TASK_DETAIL = 'tasks/:code',
  MEMBERS = 'members',
  API_KEYS = 'api-keys',
  DOWNLOADS = 'downloads',
}
