-- CreateTable
CREATE TABLE `TB_LABEL` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `name` VARCHAR(60) NOT NULL,
    `color` VARCHAR(20) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TB_LABEL_companyId_idx`(`companyId`),
    UNIQUE INDEX `TB_LABEL_companyId_name_key`(`companyId`, `name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_DOCUMENT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `body` LONGTEXT NOT NULL,
    `type` ENUM('SPEC', 'PLAN', 'NOTES', 'ADR', 'OTHER') NOT NULL DEFAULT 'SPEC',
    `version` INTEGER NOT NULL DEFAULT 1,
    `projectId` INTEGER NULL,
    `taskId` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,

    INDEX `TB_DOCUMENT_companyId_idx`(`companyId`),
    INDEX `TB_DOCUMENT_projectId_idx`(`projectId`),
    INDEX `TB_DOCUMENT_taskId_idx`(`taskId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_COMMENT` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `taskId` INTEGER NOT NULL,
    `authorId` INTEGER NOT NULL,
    `body` TEXT NOT NULL,
    `viaApiKeyId` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TB_COMMENT_companyId_idx`(`companyId`),
    INDEX `TB_COMMENT_taskId_idx`(`taskId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_TASK_DEPENDENCY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `blockerId` INTEGER NOT NULL,
    `blockedId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TB_TASK_DEPENDENCY_companyId_idx`(`companyId`),
    UNIQUE INDEX `TB_TASK_DEPENDENCY_blockerId_blockedId_key`(`blockerId`, `blockedId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_ACTIVITY_LOG` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `actorUserId` INTEGER NOT NULL,
    `viaApiKeyId` INTEGER NULL,
    `entityType` VARCHAR(40) NOT NULL,
    `entityId` INTEGER NOT NULL,
    `action` VARCHAR(60) NOT NULL,
    `changes` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TB_ACTIVITY_LOG_companyId_idx`(`companyId`),
    INDEX `TB_ACTIVITY_LOG_entityType_entityId_idx`(`entityType`, `entityId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_WEBHOOK` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `url` VARCHAR(500) NOT NULL,
    `secret` VARCHAR(120) NULL,
    `events` JSON NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TB_WEBHOOK_companyId_idx`(`companyId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_IDEMPOTENCY_KEY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `companyId` INTEGER NOT NULL,
    `key` VARCHAR(120) NOT NULL,
    `response` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `TB_IDEMPOTENCY_KEY_companyId_key_key`(`companyId`, `key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_TaskLabels` (
    `A` INTEGER NOT NULL,
    `B` INTEGER NOT NULL,

    UNIQUE INDEX `_TaskLabels_AB_unique`(`A`, `B`),
    INDEX `_TaskLabels_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TB_LABEL` ADD CONSTRAINT `TB_LABEL_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_DOCUMENT` ADD CONSTRAINT `TB_DOCUMENT_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_DOCUMENT` ADD CONSTRAINT `TB_DOCUMENT_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `TB_PROJECT`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_DOCUMENT` ADD CONSTRAINT `TB_DOCUMENT_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `TB_TASK`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_COMMENT` ADD CONSTRAINT `TB_COMMENT_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_COMMENT` ADD CONSTRAINT `TB_COMMENT_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `TB_TASK`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_COMMENT` ADD CONSTRAINT `TB_COMMENT_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `USERS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_TASK_DEPENDENCY` ADD CONSTRAINT `TB_TASK_DEPENDENCY_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_TASK_DEPENDENCY` ADD CONSTRAINT `TB_TASK_DEPENDENCY_blockerId_fkey` FOREIGN KEY (`blockerId`) REFERENCES `TB_TASK`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_TASK_DEPENDENCY` ADD CONSTRAINT `TB_TASK_DEPENDENCY_blockedId_fkey` FOREIGN KEY (`blockedId`) REFERENCES `TB_TASK`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_ACTIVITY_LOG` ADD CONSTRAINT `TB_ACTIVITY_LOG_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TB_WEBHOOK` ADD CONSTRAINT `TB_WEBHOOK_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `TB_COMPANY`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_TaskLabels` ADD CONSTRAINT `_TaskLabels_A_fkey` FOREIGN KEY (`A`) REFERENCES `TB_LABEL`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_TaskLabels` ADD CONSTRAINT `_TaskLabels_B_fkey` FOREIGN KEY (`B`) REFERENCES `TB_TASK`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
